In [2]:
import pandas as pd

In [3]:
co2_df = pd.read_csv(r'./data/CO2 Emissions_Canada.csv')

---

## Data Attributes

* Make - Company of the vehicle

* Model - Car Model
    * 4WD/4X4 = Four-wheel drive 
    * AWD = All-wheel drive 
    * FFV = Flexible-fuel vehicle 
    * SWB = Short wheelbase 
    * LWB = Long wheelbase 
    * EWB = Extended wheelbase


* Vehicle Class - Class of vehicle depending on their utility, capacity and weight

* Engine Size(L) - Size of engine used in Litre

* Cylinders - Number of cylinders

* Transmission - Transmission type with number of gears
    * A = Automatic
    * AM = Automated manual
    * AS = Automatic with select shift
    * AV = Continuously variable
    * M = Manual
    * 3 to 10 = Number of gears

* Fuel Type: X = Regular gasoline(petrol), Z = Premium gasoline, D = Diesel, E = Ethanol(E85), N = Natural gas(CNG/LNG)

* Fuel Consumption City (L/100 km) - Fuel consumption in city roads (L/100 km)

* Fuel Consumption Hwy (L/100 km) - Fuel consumption in highways (L/100 km)

* Fuel Consumption Comb (L/100 km) - The combined fuel consumption (55% city, 45% highway) is shown in L/100 km

* Fuel Consumption Comb (mpg) - The combined fuel consumption in both city and highway is shown in mile per gallon(mpg)

* City and highway fuel consumption ratings are shown in litres per 100 kilometres (L/100 km) - the combined rating (55% city, 45% hwy) is shown in L/100 km and in miles per gallon (mpg)

* CO2 Emissions(g/km) - The tailpipe emissions of carbon dioxide (in grams per kilometre) for combined city and highway driving

---

In [35]:
co2_df.sample(5)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
4904,HYUNDAI,SANTA FE,SUV - SMALL,3.3,6,AS6,X,12.9,9.4,11.3,25,265
3372,BENTLEY,CONTINENTAL GT CONVERTIBLE,SUBCOMPACT,6.0,12,AS8,Z,19.6,11.7,16.0,18,375
6660,CADILLAC,CT5 AWD,MID-SIZE,2.0,4,AS10,Z,11.0,7.7,9.5,30,221
2835,KIA,FORTE,MID-SIZE,2.0,4,M6,X,9.8,6.9,8.5,33,198
3328,ASTON MARTIN,RAPIDE S,SUBCOMPACT,6.0,12,A8,Z,16.7,10.9,14.1,20,331

In [36]:
co2_df['Transmission'].value_counts()

Transmission
AS6     1324
AS8     1211
M6       901
A6       789
A8       490
AM7      445
A9       339
AS7      319
AV       295
M5       193
AS10     168
AM6      132
AV7      118
AV6      113
M7        91
A5        84
AS9       77
A4        65
AM8       62
A7        53
AV8       39
A10       31
AS5       26
AV10      11
AM5        4
AM9        3
AS4        2
Name: count, dtype: int64

In [32]:
co2_df['Cylinders'].value_counts()

Cylinders
4     3220
6     2446
8     1402
12     151
3       95
10      42
5       26
16       3
Name: count, dtype: int64

In [31]:
co2_df.groupby('Make')['Engine Size(L)'].median().sort_values(ascending=False).head(10)

Make
SRT              8.40
BUGATTI          8.00
ROLLS-ROYCE      6.65
BENTLEY          6.00
GMC              5.30
ASTON MARTIN     5.20
LAMBORGHINI      5.20
MERCEDES-BENZ    4.00
CHEVROLET        3.60
CADILLAC         3.60
Name: Engine Size(L), dtype: float64

In [17]:
co2_df['Vehicle Class'].value_counts()

Vehicle Class
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: count, dtype: int64

In [8]:
co2_df['Make'].value_counts().head(10)

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
Name: count, dtype: int64

In [16]:
co2_df.groupby('Model')['Model'].count().sort_values(ascending=False).head(10)

Model
F-150 FFV        32
F-150 FFV 4X4    32
MUSTANG          27
FOCUS FFV        24
SONIC 5          20
F-150 4X4        20
F-150            20
SONIC            20
ACCORD           19
ATS              19
Name: Model, dtype: int64

In [5]:
co2_df.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [34]:
co2_df[co2_df.duplicated()].head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
1075,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
1076,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
1081,ALFA ROMEO,4C,TWO-SEATER,1.8,4,AM6,Z,9.7,6.9,8.4,34,193
1082,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
1084,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
1086,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
1104,AUDI,A6 QUATTRO,MID-SIZE,3.0,6,AS8,Z,12.8,8.6,10.9,26,251
1105,AUDI,A6 QUATTRO TDI (modified),MID-SIZE,3.0,6,AS8,D,9.8,6.2,8.1,35,217
1107,AUDI,A7 QUATTRO TDI (modified),MID-SIZE,3.0,6,AS8,D,9.8,6.2,8.1,35,217
1110,AUDI,A8 TDI (modified),MID-SIZE,3.0,6,AS8,D,9.8,6.5,8.4,34,224