## Import Libraries

In [4]:
# For data handling
import pandas as pd
import numpy as np

import seaborn as sns

Let's load the dataset:

In [3]:
co2_df = pd.read_csv(r'./data/co2_emissions.csv')

---

## Data Attributes

* Make - Company of the vehicle

* Model - Car Model
    * 4WD/4X4 = Four-wheel drive 
    * AWD = All-wheel drive 
    * FFV = Flexible-fuel vehicle 
    * SWB = Short wheelbase 
    * LWB = Long wheelbase 
    * EWB = Extended wheelbase


* Vehicle Class - Class of vehicle depending on their utility, capacity and weight

* Engine Size(L) - Size of engine used in Litre

* Cylinders - Number of cylinders

* Transmission - Transmission type with number of gears
    * A = Automatic
    * AM = Automated manual
    * AS = Automatic with select shift
    * AV = Continuously variable
    * M = Manual
    * 3 to 10 = Number of gears

* Fuel Type: X = Regular gasoline(petrol), Z = Premium gasoline, D = Diesel, E = Ethanol(E85), N = Natural gas(CNG/LNG)

* Fuel Consumption City (L/100 km) - Fuel consumption in city roads (L/100 km)

* Fuel Consumption Hwy (L/100 km) - Fuel consumption in highways (L/100 km)

* Fuel Consumption Comb (L/100 km) - The combined fuel consumption (55% city, 45% highway) is shown in L/100 km

* Fuel Consumption Comb (mpg) - The combined fuel consumption in both city and highway is shown in mile per gallon(mpg)

* City and highway fuel consumption ratings are shown in litres per 100 kilometres (L/100 km) - the combined rating (55% city, 45% hwy) is shown in L/100 km and in miles per gallon (mpg)

* CO2 Emissions(g/km) - The tailpipe emissions of carbon dioxide (in grams per kilometre) for combined city and highway driving

---

- info
- Check NULLs
- Remove unnecessary cols
- Deal with duplicates
- Check stats
- Check corr

---

Let's take a quick look at the DataFrame:

In [4]:
co2_df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248


Let's check the dataset structure;\
checking column types, non-null counts and memory usage, to spot missing values and columns stored as the wrong dtype before any cleaning:

In [5]:
co2_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7385 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              7385 non-null   str
 1   Model                             7385 non-null   str
 2   Vehicle Class                     7385 non-null   str
 3   Engine Size(L)                    7385 non-null   float64
 4   Cylinders                         7385 non-null   int64
 5   Transmission                      7385 non-null   str
 6   Fuel Type                         7385 non-null   str
 7   Fuel Consumption City (L/100 km)  7385 non-null   float64
 8   Fuel Consumption Hwy (L/100 km)   7385 non-null   float64
 9   Fuel Consumption Comb (L/100 km)  7385 non-null   float64
 10  Fuel Consumption Comb (mpg)       7385 non-null   int64
 11  CO2 Emissions(g/km)               7385 non-null   int64
dtypes: float64(4), int64(3), str(5)
memory usage: 692.5 KB

**Observation:**
- We have 12 columns.
- There are five **`str`** columns: `Make`, `Model`, `Vehicle Class`, `Transmission`, and `Fuel Type`
- There are four **`float64`** columns: `Engine Size(L)`, `Fuel Consumption City (L/100 km)`, `Fuel Consumption Hwy (L/100 km)`, and\
`Fuel Consumption Comb (L/100 km)`
- There are three **`int64`** columns: `Cylinders`, `Fuel Consumption Comb (mpg)`, and `CO2 Emissions(g/km)`
- There are no missing values values in the dataset.

**Next:** Drop unnecessary columns:

We have two same columns `Fuel Consumption Comb (mpg)` and `Fuel Consumption Comb (L/100 km)` in different units.\
Since other columns are in **`L`**, let's drop `Fuel Consumption Comb (mpg)`:

In [6]:
co2_df = co2_df.drop('Fuel Consumption Comb (mpg)', axis=1)

Now we have 11 columns including `Fuel Consumption Comb` column following the consistent unit `litres per 100 kilometres`.

**Next:** Let's check if we have duplicates:

In [7]:
co2_df.duplicated().sum()

np.int64(1103)

We have `1103` duplicate rows whcih is `~15%` of the dataset. I can’t tell whether they’re actual errors or just legitimate repeated records since
there is no additional information. So, it's resonable to drop them because in train-test split the same record could end up in both sets which will make our test score look better than it really is, because the model has already seen those exact rows.

**Next:** Let's drop duplicate rows:

In [8]:
co2_df = co2_df.drop_duplicates()

In [9]:
# Verify duplicates are gone
print("duplicates:",co2_df.duplicated().sum())
print("co2_df.shape:",co2_df.shape)

duplicates: 0
co2_df.shape: (6282, 11)

After dropping the duplicates there are 7,385 → 6,282 rows left. Which means if some duplicates were real separate cars, we removed real observations.

**Next:** Let's check stats of the dataset:

In [10]:
co2_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Engine Size(L),6282.0,3.161812,1.365201,0.9,2.0,3.0,3.7,8.4
Cylinders,6282.0,5.618911,1.846250,3.0,4.0,6.0,6.0,16.0
Fuel Consumption City (L/100 km),6282.0,12.610220,3.553066,4.2,10.1,12.1,14.7,30.6
Fuel Consumption Hwy (L/100 km),6282.0,9.070583,2.278884,4.0,7.5,8.7,10.3,20.6
Fuel Consumption Comb (L/100 km),6282.0,11.017876,2.946876,4.1,8.9,10.6,12.7,26.1
CO2 Emissions(g/km),6282.0,251.157752,59.290426,96.0,208.0,246.0,289.0,522.0

In [21]:
co2_df.corr(numeric_only=True)

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
Engine Size(L),1.000000,0.928843,0.834228,0.766817,0.820146,0.854802
Cylinders,0.928843,1.000000,0.801277,0.717647,0.781099,0.834687
Fuel Consumption City (L/100 km),0.834228,0.801277,1.000000,0.950811,0.994052,0.918756
Fuel Consumption Hwy (L/100 km),0.766817,0.717647,0.950811,1.000000,0.978607,0.883424
Fuel Consumption Comb (L/100 km),0.820146,0.781099,0.994052,0.978607,1.000000,0.916840
CO2 Emissions(g/km),0.854802,0.834687,0.918756,0.883424,0.916840,1.000000

In [ ]:
co2_df.to_csv('./data/co2_cleaned.csv', index=False)